(define str "hello, world")
(write str)
(write (string? str))
(write (string-length str))
(write (string-ref str 0))
(write (string-ref str 1))
(write (string-ref str 2))
(write (string-ref str 3))
(write (string-ref str 4))
(write (string->number "0"))
(write (string->number "1"))
(write (string->number "-1"))
(write (string->list str))
