(define vec #(1 2 3))
(display vec)
(display (vector? 1))
(display (vector? "hello"))
(display (vector? '(1 2 3)))
(display (vector? vec))
(display (vector-length vec))
(display (vector-ref vec 0))
(display (vector-ref vec 1))
(display (vector-ref vec 2))
(vector-set! vec 0 4)
(vector-set! vec 1 5)
(vector-set! vec 2 6)
(display vec)
(display (vector-length vec))
(display (vector-ref vec 0))
(display (vector-ref vec 1))
(display (vector-ref vec 2))
